Models/SanPham.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trang_web_ban_dien_thoai.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.ChiTietDonHangs = new HashSet<ChiTietDonHang>();
        }
    
        public int MaSanPham { get; set; }
        public int MaLoaiSanPham { get; set; }
        public int MaNhaSanXuat { get; set; }
        public string TenSanPham { get; set; }
        public string CauHinh { get; set; }
        public string HinhChinh { get; set; }
        public string Hinh1 { get; set; }
        public string Hinh2 { get; set; }
        public string Hinh3 { get; set; }
        public string Hinh4 { get; set; }
        public Nullable<double> Gia { get; set; }
        public Nullable<int> SoLuongDaBan { get; set; }
        public Nullable<int> LuotView { get; set; }
        public string TinhTrang { get; set; }
        public Nullable<int> Danhgia { get; set; }
        public Nullable<int> Soluong { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDonHang> ChiTietDonHangs { get; set; }
        public virtual LoaiSanPham LoaiSanPham { get; set; }
        public virtual NhaSanXuat NhaSanXuat { get; set; }
    }
}

Areas/admin/Controllers/SanPhamsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Trang_web_ban_dien_thoai.Models;

namespace Trang_web_ban_dien_thoai.Areas.admin.Controllers
{
    public class SanPhamsController : Controller
    {
        private ShopOnlineEntities db = new ShopOnlineEntities();

        // GET: admin/SanPhams
        public ActionResult Index()
        {
            var sanPhams = db.SanPhams.Include(s => s.LoaiSanPham).Include(s => s.NhaSanXuat);
            return View(sanPhams.ToList());
        }

        // GET: admin/SanPhams/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SanPham sanPham = db.SanPhams.Find(id);
            if (sanPham == null)
            {
                return HttpNotFound();
            }
            return View(sanPham);
        }

        // GET: admin/SanPhams/Create
        public ActionResult Create()
        {
            ViewBag.MaLoaiSanPham = new SelectList(db.LoaiSanPhams, "MaLoaiSanPham", "TenLoaiSanPham");
            ViewBag.MaNhaSanXuat = new SelectList(db.NhaSanXuats, "MaNhaSanXuat", "TenNhaSanXuat");
            return View();
        }

        // POST: admin/SanPhams/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaSanPham,MaLoaiSanPham,MaNhaSanXuat,TenSanPham,CauHinh,HinhChinh,Hinh1,Hinh2,Hinh3,Hinh4,Gia,SoLuongDaBan,LuotView,TinhTrang,Danhgia,Soluong")] SanPham sanPham, HttpPostedFileBase HinhChinh)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    if (HinhChinh.ContentLength > 0)
                    {
                        string _FileName = Path.GetFileName(HinhChinh.FileName);
                        string _path = Path.Combine(Server.MapPath("~/Asset/images"), _FileName);
                        HinhChinh.SaveAs(_path);
                        sanPham.HinhChinh = _FileName;
                    }
                    db.SanPhams.Add(sanPham);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                catch
                {
                    ViewBag.Message = "không thành công!!";
                }
            }

            ViewBag.MaLoaiSanPham = new SelectList(db.LoaiSanPhams, "MaLoaiSanPham", "TenLoaiSanPham", sanPham.MaLoaiSanPham);
            ViewBag.MaNhaSanXuat = new SelectList(db.NhaSanXuats, "MaNhaSanXuat", "TenNhaSanXuat", sanPham.MaNhaSanXuat);
            return View(sanPham);
        }

        // GET: admin/SanPhams/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SanPham sanPham = db.SanPhams.Find(id);
            if (sanPham == null)
            {
                return HttpNotFound();
            }
            ViewBag.MaLoaiSanPham = new SelectList(db.LoaiSanPhams, "MaLoaiSanPham", "TenLoaiSanPham", sanPham.MaLoaiSanPham);
            ViewBag.MaNhaSanXuat = new SelectList(db.NhaSanXuats, "MaNhaSanXuat", "TenNhaSanXuat", sanPham.MaNhaSanXuat);
            return View(sanPham);
        }

        // POST: admin/SanPhams/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaSanPham,MaLoaiSanPham,MaNhaSanXuat,TenSanPham,CauHinh,HinhChinh,Hinh1,Hinh2,Hinh3,Hinh4,Gia,SoLuongDaBan,LuotView,TinhTrang,Danhgia,Soluong")] SanPham sanPham)
        {
            if (ModelState.IsValid)
            {
                db.Entry(sanPham).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MaLoaiSanPham = new SelectList(db.LoaiSanPhams, "MaLoaiSanPham", "TenLoaiSanPham", sanPham.MaLoaiSanPham);
            ViewBag.MaNhaSanXuat = new SelectList(db.NhaSanXuats, "MaNhaSanXuat", "TenNhaSanXuat", sanPham.MaNhaSanXuat);
            return View(sanPham);
        }

        // GET: admin/SanPhams/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SanPham sanPham = db.SanPhams.Find(id);
            if (sanPham == null)
            {
                return HttpNotFound();
            }
            return View(sanPham);
        }

        // POST: admin/SanPhams/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            SanPham sanPham = db.SanPhams.Find(id);
            db.SanPhams.Remove(sanPham);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Areas/admin/Views/SanPhams/Create.cshtml
@model Trang_web_ban_dien_thoai.Models.SanPham

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/admin/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm("Create", "SanPhams", FormMethod.Post, new { enctype = "multipart/form-data" })) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>SanPham</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.MaLoaiSanPham, "MaLoaiSanPham", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MaLoaiSanPham", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaLoaiSanPham, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaNhaSanXuat, "MaNhaSanXuat", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MaNhaSanXuat", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaNhaSanXuat, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TenSanPham, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenSanPham, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenSanPham, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CauHinh, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CauHinh, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CauHinh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HinhChinh, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.HinhChinh, null, new { type = "file", @class = "form-control" })
                @Html.ValidationMessageFor(model => model.HinhChinh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Hinh1, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Hinh1, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Hinh1, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Hinh2, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Hinh2, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Hinh2, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Hinh3, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Hinh3, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Hinh3, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Hinh4, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Hinh4, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Hinh4, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Gia, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Gia, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Gia, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SoLuongDaBan, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SoLuongDaBan, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SoLuongDaBan, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LuotView, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LuotView, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LuotView, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TinhTrang, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TinhTrang, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TinhTrang, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Danhgia, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Danhgia, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Danhgia, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Soluong, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Soluong, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Soluong, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Areas/admin/Views/SanPhams/Delete.cshtml
@model Trang_web_ban_dien_thoai.Models.SanPham

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/admin/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>SanPham</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TenSanPham)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenSanPham)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CauHinh)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CauHinh)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HinhChinh)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HinhChinh)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Hinh1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Hinh1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Hinh2)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Hinh2)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Hinh3)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Hinh3)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Hinh4)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Hinh4)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Gia)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Gia)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SoLuongDaBan)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SoLuongDaBan)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LuotView)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LuotView)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TinhTrang)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TinhTrang)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Danhgia)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Danhgia)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Soluong)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Soluong)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LoaiSanPham.TenLoaiSanPham)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LoaiSanPham.TenLoaiSanPham)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NhaSanXuat.TenNhaSanXuat)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NhaSanXuat.TenNhaSanXuat)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Areas/admin/Views/SanPhams/Details.cshtml
@model Trang_web_ban_dien_thoai.Models.SanPham

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/admin/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>SanPham</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TenSanPham)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenSanPham)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CauHinh)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CauHinh)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HinhChinh)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HinhChinh)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Hinh1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Hinh1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Hinh2)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Hinh2)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Hinh3)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Hinh3)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Hinh4)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Hinh4)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Gia)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Gia)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SoLuongDaBan)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SoLuongDaBan)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LuotView)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LuotView)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TinhTrang)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TinhTrang)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Danhgia)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Danhgia)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Soluong)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Soluong)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LoaiSanPham.TenLoaiSanPham)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LoaiSanPham.TenLoaiSanPham)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NhaSanXuat.TenNhaSanXuat)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NhaSanXuat.TenNhaSanXuat)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.MaSanPham }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Areas/admin/Views/SanPhams/Index.cshtml
@model IEnumerable<Trang_web_ban_dien_thoai.Models.SanPham>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/admin/Views/Shared/_Layout.cshtml";
}

<h2>Sản phẩm</h2>

<div class="btn btn-info">
    @Html.ActionLink("Create New", "Create")
</div>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.TenSanPham)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CauHinh)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.HinhChinh)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Gia)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SoLuongDaBan)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LuotView)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TinhTrang)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Danhgia)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Soluong)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LoaiSanPham.TenLoaiSanPham)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NhaSanXuat.TenNhaSanXuat)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.TenSanPham)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CauHinh)
        </td>
        <td>
            <img src="~/Asset/images/@item.HinhChinh" style="max-width:100px;max-height:100px"/>
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Gia)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SoLuongDaBan)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LuotView)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TinhTrang)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Danhgia)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Soluong)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LoaiSanPham.TenLoaiSanPham)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NhaSanXuat.TenNhaSanXuat)
        </td>
        <td style="display:flex">
            @Html.ActionLink("Edit", "Edit", new { id = item.MaSanPham }, new { @class = "btn btn-primary" }) 
            @Html.ActionLink("Details", "Details", new { id = item.MaSanPham }, new { @class = "btn btn-info" }) 
            @Html.ActionLink("Delete", "Delete", new { id = item.MaSanPham }, new { @class = "btn btn-danger" })
        </td>
    </tr>
}

</table>